# Site settings
name: Roshan Ramkeesoon
email: rramkeesoon93@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Roshan, Ramkeesoon, Roshan Ramkeesoon, Ramkeeson, Software Engineer, Machine Learning Engineer, TensorFlow, PyTorch, Python, Machine Learning, Deep Learning, Federated Learning"
skills: "Data Scientist in Seattle, WA"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: github
    url: https://github.com/r-o-s-h-a-n
  - title: linkedin
    url: https://www.linkedin.com/in/roshanr1/
  - title: medium
    url: https://medium.com/@rramkeesoon93
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 003171
  primary-rgb: "13, 58, 95"
  secondary: 120F07
  secondary-dark: 120F07
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
